### ISSUE TITLE
Need some sort of test isolation

### ISSUE THREAD

**Issue by pbaughman** [ApexAI/apex_rostest#32]
A potential issue I'm starting to encounter - using add_apex_launchtest cmake macro may cause multiple tests to run in parallel when you do `colcon test`.  If these tests publish data on the same topics (spoiler alert, ours do!) they can conflict with one-another.

We could write our generate_test_description function to put all of the nodes in a unique namespace or carefully remap topics, but I'm wondering if there's something apex_launchtest can do for isolation.

@wjwwood @hidmic Can we do something with the launch description after it's generated, or maybe something with the launch service when we run it to get some sort of isolation?  Can we jam everything into a unique namespace and have that be transparent to the nodes being run?  Is there some other mechanism of isolation I'm not considering?  Doing it at the DDS level is pretty DDS implementation specific, I think.

**Comment by hidmic** [comment]
We were talking  exactly about this with @wjwwood earlier today. ROS 1 `rostest` used to spin up separate masters. On ROS 2, one option would be to use unique  `$ROS_DOMAIN_ID`s for each test run. 

Any other way you can think of William?

**Comment by pbaughman** [comment]
@hidmic We might need some cmake magic to coordinate ROS_DOMAIN_ID for multiple tests.  In ROS1 there were enough port numbers that you could be reasonably confident you wouldn't collide by picking randomly.  My understanding of ROS_DOMAIN_IDs is that there are 100 or 255 (or some other fairly low number) of them to choose from, so picking randomly is a recipe for collisions

**Comment by wjwwood** [comment]
Even in ROS 1, the port numbers were picked only within a single cmake package, if you ran the tests from multiple packages in parallel it would still collide. That's just not going to work in my opinion. ROS 1's rostest was meant to parallelize within a single package, so it could ensure no collisions occurred.

The domain id is the best way to have tests run in parallel. For now we just don't run tests in parallel in our CI (as far as I know).

Putting things into namespaces is an interesting idea, but unfortunately it doesn't cover cases where absolute topic names are being used. The domain id is really the "right way" to separate the unrelated tests.

**Comment by pbaughman** [comment]
@hidmic I talked to William IRL and he suggested having apex_launchtest use the ROS_DOMAIN_ID for isolation but also check that it's available by acquiring a high number port that's `some_fixed_number` + `ROS_DOMAIN_ID` so that multiple instances of apex_launchtest don't accidentally collide

**Comment by pbaughman** [comment]
Merged: https://github.com/ApexAI/apex_rostest/pull/33

**Comment by dirk-thomas** [comment]
See ros2/launch#240 making this opt-in rather than opt-out.
