### ISSUE TITLE
Parametrize the test description

### ISSUE THREAD

**Issue by pbaughman** [ApexAI/apex_rostest#38]
Do something like pytests @pytest.mark.parametrize for the launch description so we can easily run tests like this one: https://github.com/ros2/system_tests/blob/a5d2c6daffe1ffd9baf39186f3b442a38fcffb35/test_communication/test/test_publisher_subscriber.py.in

#### Edge cases to check (WIP)
 - [x] ctrl+c during a parametrized test run should exit all runs.  **Note** This was done by doing an early-out any time the processes under test dies before the tests finish.  Maybe not optimal
 - [ ] Mixing launch descriptions that require command-line arguments with ones that don't
 - [x] give a good error message if the argument in generate_test_description doesn't match the argname in the decorator
 - [x] give a good error message if parametrize has too many different args
 - [x] give a good error message if paraetrize has too few args

**Comment by pbaughman** [comment]
@hidmic I've started this on our fork, mainly so I can use the CI that's already set up.  I'll do the necessary work to port it to the ros2/launch fork after I get a working prototype that you can throw darts out

**Comment by hidmic** [comment]
That's great @pbaughman, thank you.

**Comment by pbaughman** [comment]
Merged here: https://github.com/ApexAI/apex_rostest/pull/39
