### ISSUE TITLE
Too many ways to assert on output/exit code

### ISSUE THREAD

**Issue by pbaughman** [ApexAI/apex_rostest#7]
There are a few places in apex_rostest that are concerned with identifying processes to look at exit codes or for matching stdout.  Each one works a little differently.  We should refactor this to have a common mechanism/signature on these asserts

APIs that should match one-another:

#### Stdout asserts
- [x] `assertInStdout(proc_output, msg, node, cmd_args, *, strict_node_matching=True)`
- [x] `assertSequentialStdout(proc_output, node)`
- [x] `ActiveIoHandler.assertWaitFor(msg, timeout)`
- [x] `apex_launchtest.event_handlers.StdoutReadyListener(proc_name, ready_txt)`

#### Exit Code assertions
- [x] `assertExitCodes(proc_info, allowable_exit_codes)`
- [x] 'ActiveProcInfoHandler.assertWaitForShutdown(*, process, timeout)`

### Discussion Items
 * It might be worth deprecating the use of process names + arguments to identify a process.  Maybe all of the assert methods should just use an ExecuteProcess object as the key to identify a process
 * Some asserts are free functions and some are methods.  Is there a way to simplify that?

**Comment by hidmic** [comment]
It'd be nice for exit code assertions to be implicit in certain cases. Having to assert that e.g. a `GTest` action exits with a non-zero code is a bit redundant.

**Comment by pbaughman** [comment]
@hidmic This should be pretty easy to add once test actions go in.  There are a few corner cases that make it a little tricky, but I'll discuss those in https://github.com/ApexAI/apex_rostest/issues/19

**Comment by pbaughman** [comment]
Oh, I mis-understood 19 when I glanced at it. . . I'll open a new issue for this [here](https://github.com/ApexAI/apex_rostest/issues/21)
